const initialUsers = [
    {
      id: 1,
      name: "Sasi",
      email: "user1@example.com",
      mobile:9952763312,
      monthly_payment: 500,
      borrowed_amount: 0,
      borrowedOnce: false,
      payment_history: [
        { month: "October", paid_amount: 500, borrowed: 0 },
        { month: "November", paid_amount: 0, borrowed: 0 },
        { month: "December", paid_amount: 0, borrowed: 0 },
        { month: "January", paid_amount: 0, borrowed: 0 },
        { month: "February", paid_amount: 0, borrowed: 0 },
        { month: "March", paid_amount: 0, borrowed: 0 },
        { month: "April", paid_amount: 0, borrowed: 0 },
        { month: "May", paid_amount: 0, borrowed: 0 },
        { month: "June", paid_amount: 0, borrowed: 0 },
        { month: "July", paid_amount: 0, borrowed: 0 },
      ],
    },
    {
      id: 2,
      name: "Arun",
      email: "user2@example.com",
      mobile:8489166740,
      monthly_payment: 500,
      borrowed_amount: 0,
      borrowedOnce: false,
      payment_history: [
        { month: "October", paid_amount: 500, borrowed: 0 },
        { month: "November", paid_amount: 0, borrowed: 0 },
        { month: "December", paid_amount: 0, borrowed: 0 },
        { month: "January", paid_amount: 0, borrowed: 0 },
        { month: "February", paid_amount: 0, borrowed: 0 },
        { month: "March", paid_amount: 0, borrowed: 0 },
        { month: "April", paid_amount: 0, borrowed: 0 },
        { month: "May", paid_amount: 0, borrowed: 0 },
        { month: "June", paid_amount: 0, borrowed: 0 },
        { month: "July", paid_amount: 0, borrowed: 0 },
      ],
    },
    {
      id: 3,
      name: "Babu",
      email: "user2@example.com",
      mobile:9443564019,
      monthly_payment: 500,
      borrowed_amount: 0,
      borrowedOnce: false,
      payment_history: [
        { month: "October", paid_amount: 500, borrowed: 0 },
        { month: "November", paid_amount: 0, borrowed: 0 },
        { month: "December", paid_amount: 0, borrowed: 0 },
        { month: "January", paid_amount: 0, borrowed: 0 },
        { month: "February", paid_amount: 0, borrowed: 0 },
        { month: "March", paid_amount: 0, borrowed: 0 },
        { month: "April", paid_amount: 0, borrowed: 0 },
        { month: "May", paid_amount: 0, borrowed: 0 },
        { month: "June", paid_amount: 0, borrowed: 0 },
        { month: "July", paid_amount: 0, borrowed: 0 },
      ],
    },
    {
      id: 4,
      name: "Vignesh",
      email: "user2@example.com",
      mobile:9500955898,
      monthly_payment: 500,
      borrowed_amount: 0,
      borrowedOnce: false,
      payment_history: [
        { month: "October", paid_amount: 500, borrowed: 0 },
        { month: "November", paid_amount: 0, borrowed: 0 },
        { month: "December", paid_amount: 0, borrowed: 0 },
        { month: "January", paid_amount: 0, borrowed: 0 },
        { month: "February", paid_amount: 0, borrowed: 0 },
        { month: "March", paid_amount: 0, borrowed: 0 },
        { month: "April", paid_amount: 0, borrowed: 0 },
        { month: "May", paid_amount: 0, borrowed: 0 },
        { month: "June", paid_amount: 0, borrowed: 0 },
        { month: "July", paid_amount: 0, borrowed: 0 },
      ],
    },
    {
      id: 5,
      name: "Dhaya",
      email: "user2@example.com",
      mobile:6383342338,
      monthly_payment: 500,
      borrowed_amount: 0,
      borrowedOnce: false,
      payment_history: [
        { month: "October", paid_amount: 500, borrowed: 0 },
        { month: "November", paid_amount: 0, borrowed: 0 },
        { month: "December", paid_amount: 0, borrowed: 0 },
        { month: "January", paid_amount: 0, borrowed: 0 },
        { month: "February", paid_amount: 0, borrowed: 0 },
        { month: "March", paid_amount: 0, borrowed: 0 },
        { month: "April", paid_amount: 0, borrowed: 0 },
        { month: "May", paid_amount: 0, borrowed: 0 },
        { month: "June", paid_amount: 0, borrowed: 0 },
        { month: "July", paid_amount: 0, borrowed: 0 },
      ],
    },
    {
      id: 6,
      name: "Bajja",
      email: "user2@example.com",
      mobile:9003669326,
      monthly_payment: 500,
      borrowed_amount: 0,
      borrowedOnce: false,
      payment_history: [
        { month: "October", paid_amount: 500, borrowed: 0 },
        { month: "November", paid_amount: 0, borrowed: 0 },
        { month: "December", paid_amount: 0, borrowed: 0 },
        { month: "January", paid_amount: 0, borrowed: 0 },
        { month: "February", paid_amount: 0, borrowed: 0 },
        { month: "March", paid_amount: 0, borrowed: 0 },
        { month: "April", paid_amount: 0, borrowed: 0 },
        { month: "May", paid_amount: 0, borrowed: 0 },
        { month: "June", paid_amount: 0, borrowed: 0 },
        { month: "July", paid_amount: 0, borrowed: 0 },
      ],
    },
    {
      id: 7,
      name: "Jagadeesh",
      email: "user2@example.com",
      mobile:9600678433,
      monthly_payment: 500,
      borrowed_amount: 0,
      borrowedOnce: false,
      payment_history: [
        { month: "October", paid_amount: 500, borrowed: 0 },
        { month: "November", paid_amount: 0, borrowed: 0 },
        { month: "December", paid_amount: 0, borrowed: 0 },
        { month: "January", paid_amount: 0, borrowed: 0 },
        { month: "February", paid_amount: 0, borrowed: 0 },
        { month: "March", paid_amount: 0, borrowed: 0 },
        { month: "April", paid_amount: 0, borrowed: 0 },
        { month: "May", paid_amount: 0, borrowed: 0 },
        { month: "June", paid_amount: 0, borrowed: 0 },
        { month: "July", paid_amount: 0, borrowed: 0 },
      ],
    },
    {
      id: 8,
      name: "Sheshu",
      email: "user2@example.com",
      mobile:6385587895,
      monthly_payment: 500,
      borrowed_amount: 0,
      borrowedOnce: false,
      payment_history: [
        { month: "October", paid_amount: 500, borrowed: 0 },
        { month: "November", paid_amount: 0, borrowed: 0 },
        { month: "December", paid_amount: 0, borrowed: 0 },
        { month: "January", paid_amount: 0, borrowed: 0 },
        { month: "February", paid_amount: 0, borrowed: 0 },
        { month: "March", paid_amount: 0, borrowed: 0 },
        { month: "April", paid_amount: 0, borrowed: 0 },
        { month: "May", paid_amount: 0, borrowed: 0 },
        { month: "June", paid_amount: 0, borrowed: 0 },
        { month: "July", paid_amount: 0, borrowed: 0 },
      ],
    },
    {
      id: 9,
      name: "Karthik",
      email: "user2@example.com",
      mobile:7339231885,
      monthly_payment: 500,
      borrowed_amount: 0,
      borrowedOnce: false,
      payment_history: [
        { month: "October", paid_amount: 500, borrowed: 0 },
        { month: "November", paid_amount: 0, borrowed: 0 },
        { month: "December", paid_amount: 0, borrowed: 0 },
        { month: "January", paid_amount: 0, borrowed: 0 },
        { month: "February", paid_amount: 0, borrowed: 0 },
        { month: "March", paid_amount: 0, borrowed: 0 },
        { month: "April", paid_amount: 0, borrowed: 0 },
        { month: "May", paid_amount: 0, borrowed: 0 },
        { month: "June", paid_amount: 0, borrowed: 0 },
        { month: "July", paid_amount: 0, borrowed: 0 },
      ],
    },
    {
      id: 10,
      name: "Kg",
      email: "user2@example.com",
      mobile:8248405266,
      monthly_payment: 500,
      borrowed_amount: 0,
      borrowedOnce: false,
      payment_history: [
        { month: "October", paid_amount: 500, borrowed: 0 },
        { month: "November", paid_amount: 0, borrowed: 0 },
        { month: "December", paid_amount: 0, borrowed: 0 },
        { month: "January", paid_amount: 0, borrowed: 0 },
        { month: "February", paid_amount: 0, borrowed: 0 },
        { month: "March", paid_amount: 0, borrowed: 0 },
        { month: "April", paid_amount: 0, borrowed: 0 },
        { month: "May", paid_amount: 0, borrowed: 0 },
        { month: "June", paid_amount: 0, borrowed: 0 },
        { month: "July", paid_amount: 0, borrowed: 0 },
      ],
    },
    {
      id: 11,
      name: "Manju",
      email: "user2@example.com",
      mobile:9361303932,
      monthly_payment: 500,
      borrowed_amount: 0,
      borrowedOnce: false,
      payment_history: [
        { month: "October", paid_amount: 500, borrowed: 0 },
        { month: "November", paid_amount: 0, borrowed: 0 },
        { month: "December", paid_amount: 0, borrowed: 0 },
        { month: "January", paid_amount: 0, borrowed: 0 },
        { month: "February", paid_amount: 0, borrowed: 0 },
        { month: "March", paid_amount: 0, borrowed: 0 },
        { month: "April", paid_amount: 0, borrowed: 0 },
        { month: "May", paid_amount: 0, borrowed: 0 },
        { month: "June", paid_amount: 0, borrowed: 0 },
        { month: "July", paid_amount: 0, borrowed: 0 },
      ],
    },
    {
      id: 12,
      name: "Nagesh",
      email: "user2@example.com",
      mobile: 8098424708,
      monthly_payment: 500,
      borrowed_amount: 0,
      borrowedOnce: false,
      payment_history: [
        { month: "October", paid_amount: 0, borrowed: 0 },
        { month: "November", paid_amount: 0, borrowed: 0 },
        { month: "December", paid_amount: 0, borrowed: 0 },
        { month: "January", paid_amount: 0, borrowed: 0 },
        { month: "February", paid_amount: 0, borrowed: 0 },
        { month: "March", paid_amount: 0, borrowed: 0 },
        { month: "April", paid_amount: 0, borrowed: 0 },
        { month: "May", paid_amount: 0, borrowed: 0 },
        { month: "June", paid_amount: 0, borrowed: 0 },
        { month: "July", paid_amount: 0, borrowed: 0 },
      ],
    },
    {
      id: 14,
      name: "Praveen",
      email: "user2@example.com",
      mobile: 8098425199,
      monthly_payment: 500,
      borrowed_amount: 0,
      borrowedOnce: false,
      payment_history: [
        { month: "October", paid_amount: 500, borrowed: 0 },
        { month: "November", paid_amount: 0, borrowed: 0 },
        { month: "December", paid_amount: 0, borrowed: 0 },
        { month: "January", paid_amount: 0, borrowed: 0 },
        { month: "February", paid_amount: 0, borrowed: 0 },
        { month: "March", paid_amount: 0, borrowed: 0 },
        { month: "April", paid_amount: 0, borrowed: 0 },
        { month: "May", paid_amount: 0, borrowed: 0 },
        { month: "June", paid_amount: 0, borrowed: 0 },
        { month: "July", paid_amount: 0, borrowed: 0 },
      ],
    },
    {
      id: 15,
      name: "Purshi",
      email: "user2@example.com",
      mobile: 8523918644,
      monthly_payment: 500,
      borrowed_amount: 0,
      borrowedOnce: false,
      payment_history: [
        { month: "October", paid_amount: 500, borrowed: 0 },
        { month: "November", paid_amount: 0, borrowed: 0 },
        { month: "December", paid_amount: 0, borrowed: 0 },
        { month: "January", paid_amount: 0, borrowed: 0 },
        { month: "February", paid_amount: 0, borrowed: 0 },
        { month: "March", paid_amount: 0, borrowed: 0 },
        { month: "April", paid_amount: 0, borrowed: 0 },
        { month: "May", paid_amount: 0, borrowed: 0 },
        { month: "June", paid_amount: 0, borrowed: 0 },
        { month: "July", paid_amount: 0, borrowed: 0 },
      ],
    },
    {
      id: 16,
      name: "Sandeep",
      email: "user2@example.com",
      mobile: 9566854074,
      monthly_payment: 500,
      borrowed_amount: 0,
      borrowedOnce: false,
      payment_history: [
        { month: "October", paid_amount: 500, borrowed: 0 },
        { month: "November", paid_amount: 0, borrowed: 0 },
        { month: "December", paid_amount: 0, borrowed: 0 },
        { month: "January", paid_amount: 0, borrowed: 0 },
        { month: "February", paid_amount: 0, borrowed: 0 },
        { month: "March", paid_amount: 0, borrowed: 0 },
        { month: "April", paid_amount: 0, borrowed: 0 },
        { month: "May", paid_amount: 0, borrowed: 0 },
        { month: "June", paid_amount: 0, borrowed: 0 },
        { month: "July", paid_amount: 0, borrowed: 0 },
      ],
    },
    {
      id: 17,
      name: "Sridhar",
      email: "user2@example.com",
      mobile: 9353187899,
      monthly_payment: 500,
      borrowed_amount: 0,
      borrowedOnce: false,
      payment_history: [
        { month: "October", paid_amount: 500, borrowed: 0 },
        { month: "November", paid_amount: 0, borrowed: 0 },
        { month: "December", paid_amount: 0, borrowed: 0 },
        { month: "January", paid_amount: 0, borrowed: 0 },
        { month: "February", paid_amount: 0, borrowed: 0 },
        { month: "March", paid_amount: 0, borrowed: 0 },
        { month: "April", paid_amount: 0, borrowed: 0 },
        { month: "May", paid_amount: 0, borrowed: 0 },
        { month: "June", paid_amount: 0, borrowed: 0 },
        { month: "July", paid_amount: 0, borrowed: 0 },
      ],
    },
    {
      id: 18,
      name: "Shanthakumar",
      email: "user2@example.com",
      mobile: 7871571957,
      monthly_payment: 500,
      borrowed_amount: 0,
      borrowedOnce: false,
      payment_history: [
        { month: "October", paid_amount: 500, borrowed: 0 },
        { month: "November", paid_amount: 0, borrowed: 0 },
        { month: "December", paid_amount: 0, borrowed: 0 },
        { month: "January", paid_amount: 0, borrowed: 0 },
        { month: "February", paid_amount: 0, borrowed: 0 },
        { month: "March", paid_amount: 0, borrowed: 0 },
        { month: "April", paid_amount: 0, borrowed: 0 },
        { month: "May", paid_amount: 0, borrowed: 0 },
        { month: "June", paid_amount: 0, borrowed: 0 },
        { month: "July", paid_amount: 0, borrowed: 0 },
      ],
    },
  ];

  export default initialUsers